repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml
      - id: check-added-large-files
      - id: detect-private-key
      - id: no-commit-to-branch

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.2
    hooks:
      # Linter
      - id: ruff
        args: [--fix]
      # Formatter
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.14.1"
    hooks:
      - id: mypy
        args: [--config-file=./pyproject.toml]
        # This hook's documentation says that it can't handle `--install-types`,
        # thus any dependencies must be specified manually.
        # If a new dependency is added and breaks this hook,
        # then check for stubs in https://github.com/python/typeshed/tree/main/stubs
        # If no stub is found in typeshed, then add the actual package
        # If this still doesn't work, remove the package from this hook,
        # and add an inline `# type: ignore[import-untyped]` comment wherever the package is imported.
        additional_dependencies:
          [
            pandas-stubs,
            types-requests,
            types-oauthlib,
            types-requests-oauthlib,
            types-python-dateutil,
            pytest,
            pytest-mock,
            pyspark,
            delta-spark,
            python-gitlab,
            oauth2client,
            pydrive2,
            types-PyYAML,
            slack_sdk,
          ]
